const students = [
    // Special Authorization
    { matricNumber: "U22MTH1001", name: "Admin", department: "Mathematics" },

    // Aerospace Engineering
    { matricNumber: "U24AE1015", name: "Eqbe Ebalam", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1037", name: "OLUWU JOSHEPH", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1036", name: "Onyekwuluje Benjamin", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1065", name: "Oqenyi Moses", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1018", name: "Sunday Samuel", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1038", name: "Iqbana David", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1006", name: "YUSUF ALMUBARAK", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1064", name: "David Daniel", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1008", name: "Adekilekun Islamiyah", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1067", name: "Yusuf Destiny", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1080", name: "Owuda Winifred", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1061", name: "Mcanqus Diqide", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1030", name: "NYIHEMBA HEMBAFAN", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1051", name: "MUHAMMAD SULEIMAN", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1029", name: "AYANTUNJI MICHEAL", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1075", name: "Muhammad Fauwaz", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1083", name: "Oqbonda Gospel", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1056", name: "Fredrick Dorcas", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1081", name: "Essiet Etini", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1001", name: "Felix-Clarkson Joshua", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1026", name: "Adibe Arinze", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1002", name: "Umoren Lee", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1069", name: "Adam Musa", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1043", name: "Mutari Abdulhamid", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1039", name: "Akpan Stephen", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1070", name: "Umaru Abubakar", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1032", name: "Oziqi Ozinda", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1014", name: "YUSUF AARON", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1012", name: "SLYVESTER RUTH", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1013", name: "ONIKEKO JOSHUA", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1085", name: "OKE JOSHEPH", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1005", name: "BABALOLA MUHAMMAD", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1016", name: "AKINYEMI AKINDAMOLA", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1023", name: "AMEH ISAAC", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1062", name: "Shidda Jason", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1010", name: "Damisa Moses", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1020", name: "Peter Juliet", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1078", name: "Nathaniel Jerry", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1042", name: "Jacob Jeremiah", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1024", name: "Ismaila Abdulhafiz", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1079", name: "Saqir Anas", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1074", name: "Eneje Caleb", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1031", name: "OIGABO KIT", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1047", name: "Gvanq Gallio", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1004", name: "KOLOMI FAWWAZ", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1011", name: "Morqan Yakendim", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1007", name: "Dauda Mishael", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1053", name: "Adesanya Oluwateniola", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1052", name: "MUKTAR NAZIR", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1035", name: "Aliyu Abdullahi", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1003", name: "Abdullahi Muhammed", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1058", name: "Odedele Joshua", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1073", name: "Oqbonna Samuel", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1044", name: "Aveni Enoch", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1034", name: "Abubakar Saudatu", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1054", name: "Raji Abubakry", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1063", name: "Tajuddeen Mahamud", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1045", name: "Tuqba Samuel", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1041", name: "Mairiqa Aliyu", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1059", name: "Alex Victor", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1066", name: "Salako Oluwaferanmi", department: "Aerospace Engineering" },
    { matricNumber: "U24AE1027", name: "KABIR MUHAMMAD", department: "Aerospace Engineering" },

    // Automotive Engineering (AUE)
    { matricNumber: "U24AUE1043", name: "Iqoh Francis", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1009", name: "Ekong Emediong", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1041", name: "Dunq Fenq", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1034", name: "Nden Pardam", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1048", name: "Ajah Chinonso", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1029", name: "David Berit", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1003", name: "Jimoh Toheeb", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1024", name: "Iremhimhen Majesty", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1023", name: "Kamlewechi John", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1032", name: "Shuaibu Muhammad", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1045", name: "Olajide Oyindamola", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1042", name: "Jacob Jeremiah", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1026", name: "Anvafulu Jemal", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1012", name: "Chika Treasure", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1037", name: "Abdulrahim Abbas", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1033", name: "Ojeanyah Michael", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1002", name: "Ogunyemi Adejare", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1005", name: "Ekpen-Obaseki Ronald", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1022", name: "BALOGUN OLUWATOBI", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1027", name: "Dooiro Duke", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1036", name: "Utile Thomas", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1025", name: "Achemta Boyesoko", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1001", name: "Salawu Olutayo", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1030", name: "Jimin Aaron", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1039", name: "Ameh Michael", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1031", name: "Adeqbite Almukaram", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1006", name: "Busari Aishat", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1008", name: "Echu Emmanuel", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1015", name: "Amovedo David", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1038", name: "Osaqie Divinewill", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1040", name: "Ameh Gabriel", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1010", name: "Aqa Emmanuel", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1019", name: "Richard God'sqift", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1011", name: "Sofolabo Oluwadamilola", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1014", name: "Anani Isabel", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1004", name: "Green Olavinka", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1049", name: "NKEMDIRIM KELVIN", department: "Automotive Engineering" },
    { matricNumber: "U24AUE1046", name: "Akaade Philemon", department: "Automotive Engineering" },

    // Civil Engineering (CE)
    { matricNumber: "U24CE1008", name: "Ibrahim Jeremiah", department: "Civil Engineering" },
    { matricNumber: "U24CE1032", name: "Iqhalo Favour", department: "Civil Engineering" },
    { matricNumber: "U24CE1055", name: "Sylvester Stanley", department: "Civil Engineering" },
    { matricNumber: "U24CE1038", name: "Hassan Lucky", department: "Civil Engineering" },
    { matricNumber: "U24CE1018", name: "Abdulrafiu Sunny Hassan", department: "Civil Engineering" },
    { matricNumber: "U24CE1009", name: "Jared Jukumensu", department: "Civil Engineering" },
    { matricNumber: "U24CE1007", name: "Odusanya Oluwabusayo", department: "Civil Engineering" },
    { matricNumber: "U24CE1037", name: "Olayi James", department: "Civil Engineering" },
    { matricNumber: "U24CE1027", name: "Idris Mujeeb", department: "Civil Engineering" },
    { matricNumber: "U24CE1016", name: "Sufyanu Abdurrahman", department: "Civil Engineering" },
    { matricNumber: "U24CE1034", name: "Philip Light", department: "Civil Engineering" },
    { matricNumber: "U24CE1002", name: "Misbahu Abdulmuttolib", department: "Civil Engineering" },
    { matricNumber: "U24CE1022", name: "Musafau Fareedah", department: "Civil Engineering" },
    { matricNumber: "U24CE1017", name: "Bashir Rahima", department: "Civil Engineering" },
    { matricNumber: "U24CE1051", name: "Oyewale Aisha", department: "Civil Engineering" },
    { matricNumber: "U24CE1050", name: "Yakubu Ruhullahi", department: "Civil Engineering" },
    { matricNumber: "U24CE1044", name: "Elebachi Solomon", department: "Civil Engineering" },
    { matricNumber: "U24CE1011", name: "Onyia Ebubechukwu", department: "Civil Engineering" },
    { matricNumber: "U24CE1040", name: "Dhikrullah Fadhlullah", department: "Civil Engineering" },
    { matricNumber: "U24CE1023", name: "Nasiru Abdulmalik", department: "Civil Engineering" },
    { matricNumber: "U24CE1004", name: "Hassan Ridwan", department: "Civil Engineering" },
    { matricNumber: "U24CE1001", name: "Kabiru Khalifa", department: "Civil Engineering" },
    { matricNumber: "U24CE1043", name: "Abdullahi Hosea", department: "Civil Engineering" },
    { matricNumber: "U24CE1033", name: "Ifemeje Praises", department: "Civil Engineering" },
    { matricNumber: "U24CE1053", name: "Yaroson Bello", department: "Civil Engineering" },
    { matricNumber: "U24CE1049", name: "Onimisi Ohieku", department: "Civil Engineering" },
    { matricNumber: "U24CE1012", name: "Jude-Peters Innocent", department: "Civil Engineering" },
    { matricNumber: "U24CE1031", name: "Tajudeen Habib", department: "Civil Engineering" },
    { matricNumber: "U24CE1041", name: "Chukwunenye Greatassurance", department: "Civil Engineering" },
    { matricNumber: "U24CE1015", name: "Nwovu Chioma", department: "Civil Engineering" },
    { matricNumber: "U24CE1030", name: "Shuaib Abdulhafiz", department: "Civil Engineering" },
    { matricNumber: "U24CE1042", name: "Sikirullahi Mohammed", department: "Civil Engineering" },
    { matricNumber: "U24CE1025", name: "Aqakwu Divine", department: "Civil Engineering" },
    { matricNumber: "U24CE1036", name: "Marvoms Henryhills", department: "Civil Engineering" },
    { matricNumber: "U24CE1021", name: "Udava Chika", department: "Civil Engineering" },
    { matricNumber: "U24CE1035", name: "Kwayama Shamkong", department: "Civil Engineering" },
    { matricNumber: "U24CE1048", name: "Dami Jedidiah", department: "Civil Engineering" },
    { matricNumber: "U24CE1047", name: "Ibrahim Ahmad", department: "Civil Engineering" },
    { matricNumber: "U24CE1052", name: "Oquche Damian", department: "Civil Engineering" },
    { matricNumber: "U24CE1006", name: "Oqunjobi Muazim", department: "Civil Engineering" },
    { matricNumber: "U24CE1005", name: "Abdulazeez Abdullateef", department: "Civil Engineering" },
    { matricNumber: "U24CE1014", name: "Ipusu Ruth", department: "Civil Engineering" },
    { matricNumber: "U24CE1040", name: "Saeed Mubarak", department: "Civil Engineering" },
    { matricNumber: "U24CE1029", name: "Aminu-Abatemi Bashshar", department: "Civil Engineering" },
    { matricNumber: "U24CE1020", name: "Muhammad Muhammad", department: "Civil Engineering" },
    { matricNumber: "U24CE1042", name: "Kvafa Honest", department: "Civil Engineering" },
    { matricNumber: "U24CE1045", name: "Bulus Laqhchonq", department: "Civil Engineering" },

    // Electrical/Electronic Engineering (EEE)
    { matricNumber: "U24EEE1011", name: "Oshiokhamelei Abdulsamad", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1025", name: "Otaru Daniella", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1044", name: "Balogun Emmanuel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1054", name: "Nurudeen Yusuf", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1005", name: "Udi Emmanuel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1037", name: "Daud Sa'Ad", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1021", name: "Kevin Nenfort", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1015", name: "Alackson Stephen", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1007", name: "Adamu Ibrahim", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1033", name: "Reuben Sharon", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1032", name: "Eqhrudje Israel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1017", name: "Abdullahi Mujahideen", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1018", name: "Tor Son", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1022", name: "Alexander Jathniel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1006", name: "Solomon Jinan", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1043", name: "Chryss-Ayakor Emmanuel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1002", name: "John Divine", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1016", name: "Saad Abubakar", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1050", name: "Yaroson Zahra", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1035", name: "Shemanq Japheth", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1004", name: "Babatunde Eniola", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1027", name: "Omoreqie Promise", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1028", name: "Modupe Ayomide", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1051", name: "Ukwuije Gloria", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1001", name: "Onoja Samuel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1049", name: "John Chrysantus", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1036", name: "Ibrahim Muhammad", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1017", name: "Yawale Abdullahi", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1034", name: "Falaya Armstrong", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1046", name: "Jonah Eneojo", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1052", name: "Salif Abdulrahman", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1019", name: "Abubakar Abdullah", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1008", name: "Abiade Abdulrasheed", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1047", name: "Banzaro Heinrich", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1030", name: "Okpolo Michael", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1040", name: "Abdulmalik Iman", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1039", name: "Ocheje Samuel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1024", name: "Atovebi Goodluck", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1009", name: "Ibrahim Usman", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1018", name: "Muhammad Junaid", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1031", name: "Gusikit Nanmen", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1023", name: "Shaapera James", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1003", name: "Ejike Kelachukwu", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1012", name: "Emmanuel Samuel", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1010", name: "Dilkon Nanzanq", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1013", name: "Dunq Joshua", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1048", name: "Pev Terkimbi", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1020", name: "Isah Muhammad", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1053", name: "Oluboyo Henry", department: "Electrical/Electronic Engineering" },
    { matricNumber: "U24EEE1055", name: "USMAN IBRAHIM", department: "Electrical/Electronic Engineering" },

    // Information/Computer Engineering (ICE)
    { matricNumber: "U24ICE1059", name: "Abakume Pascal", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1006", name: "Bassey Basil", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1017", name: "Olabode Oluwatimilehin", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1049", name: "Adedoyin Jethro", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1023", name: "Lawal David", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1041", name: "Samuel Mayandu", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1024", name: "Obia Samuel", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1013", name: "Adesanya Adeniyi", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1009", name: "Adadu Nelson", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1003", name: "Momodu Fadlullah", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1015", name: "Aqada John", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1037", name: "Odukoqbe Greatness", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1050", name: "Akpen Fanan", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1032", name: "Yod Shemkai", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1057", name: "Edward Eri", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1026", name: "Ali Isah", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1004", name: "Oluwafemi Bisola", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1046", name: "Audam Victor", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1019", name: "Ponsak Malcolm", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1001", name: "Idowu Samuel", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1035", name: "Obafemi Peter", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1047", name: "Turaki Muhammad", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1060", name: "Aondoakaa Raphael", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1007", name: "Chukwuji Gerald", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1005", name: "Omorefe Godsqift", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1029", name: "Idemudia Frank", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1038", name: "Olawale Farouq", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1014", name: "Akewula Taofeeq", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1020", name: "Abdulazeez Imran", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1013", name: "Abdulsalam Abdulrahman", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1031", name: "Obafemi Queen", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1028", name: "Kukoyi Hadia", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1052", name: "Kwarpo Zeenret", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1012", name: "Muhammad Shareefah", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1027", name: "Domchak Nanim", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1021", name: "Adekunle Faizah", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1043", name: "Eqbo Nmesoma", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1036", name: "Arinola Ibukunoluwa", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1044", name: "Mhambe Seerdoon", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1045", name: "Mike-Uqwuarah Nkechukwu", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1033", name: "Nwaokoro Chike", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1054", name: "Aliyu Muhammad", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1053", name: "Elisha Iqbamshi", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1055", name: "Bakare Abdullah", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1016", name: "Shehu Fukki", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1022", name: "Maha Victoria", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1010", name: "Osaqie Lewis", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1002", name: "Mohammed Yazeed", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1034", name: "Abubakar Saudatu", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1042", name: "Umar Tayyib", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1008", name: "Sani Abubakar", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1048", name: "Haruna Mainasara", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1011", name: "Wapmuk Shinna'An", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1058", name: "Freeman Light", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1056", name: "Abu Goshen", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1051", name: "Izuakor Chekwubechukwu", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1061", name: "Ibrahim Muhammad", department: "Information/Computer Engineering" },
    { matricNumber: "U24ICE1018", name: "Idiake Destiny", department: "Information/Computer Engineering" },

    // Mechanical Engineering (ME)
    { matricNumber: "U24ME1042", name: "Osivave Kelvin", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1019", name: "Abba Joshua", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1022", name: "Sadiq Hauwa", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1024", name: "Yakubu Elisha", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1055", name: "Moses Divine", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1009", name: "Uvandeamo Alison", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1045", name: "Jimoh Abdulhadi", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1044", name: "Oputa-Ajie Ifechukwudeni", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1040", name: "Ese Victor", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1033", name: "Abua Emmanuel", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1052", name: "Bulus Blessed", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1049", name: "Akpan Edima", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1041", name: "Adamu Abdullahi", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1048", name: "Apever Ivande", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1040", name: "Joseph Jubilee", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1004", name: "ISHAKU BENEDICT", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1013", name: "Nwankwo Goodnews", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1015", name: "Idris Abdul", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1040", name: "Enoch Joseph", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1012", name: "Kvasua Torkwase", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1001", name: "Bulus Stephen", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1010", name: "Gideon Hadriel", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1054", name: "Yakub Abdulsamad", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1031", name: "Utsu Francis", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1051", name: "Ojo Heritage", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1018", name: "Ahmad Abubakar", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1016", name: "Echude Daniel", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1057", name: "Okenwa Chidera", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1035", name: "Danjuma Muhammad", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1029", name: "Jamiu Abdulhakeem", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1043", name: "Adebowale Elijah", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1058", name: "Olawale Idris", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1044", name: "Yusuf Abdulhakeem", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1015", name: "MOSUGU JEREMY", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1005", name: "Sylvester Samson", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1026", name: "Nasiru Abubakar", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1050", name: "Omidiora Mosopeoluwa", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1011", name: "Daniel Erinayo", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1038", name: "Oyediran Matthew", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1056", name: "Solomon Success", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1020", name: "Mala Hyelezira", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1012", name: "Dauda Mohammed", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1037", name: "Nwaorqu Princess", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1002", name: "Chilaka David", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1008", name: "Ali Abduljabbar", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1030", name: "Anohu Chisom", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1047", name: "Abdulkadir Yusuf", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1021", name: "Yilkudi Kamji", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1014", name: "EMMANUEL IKECHUKWU", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1017", name: "FASHOLA AKINYEMI", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1059", name: "SHAIBU ONUCHE", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1001", name: "Ezeunara Nzubechukwu", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1022", name: "Atoyin Neil", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1023", name: "Adesile Oluwajomiloju", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1006", name: "Ephraim Hassan", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1056", name: "Ibrahim Ibrahim", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1025", name: "SALAMI AADIL", department: "Mechanical Engineering" },
    { matricNumber: "U24ME1046", name: "AJIBADE ABDULBASIT", department: "Mechanical Engineering" },

    // Mechatronics Engineering (MTE)
    { matricNumber: "U24MTE1037", name: "Oyelade Oyewumi", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1062", name: "Udoh Akanimo", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1022", name: "Sadiq Hauwa", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1031", name: "Danladi Prince-Michael", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1030", name: "Chukwu Princewill", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1039", name: "Oyedeyi Joel", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1059", name: "Abakume Pascal", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1024", name: "Nwaqbo Olive", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1057", name: "Onwumeru Olive", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1010", name: "Achakpa-Ikyo Terhide", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1028", name: "Maikudi Hassan", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1035", name: "Bart-Iwodi Felicia", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1060", name: "Raji-Ibraheem Muadh", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1053", name: "Yahaya Ibrahim", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1015", name: "Idris Abdul", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1055", name: "Salaudeen Abdulqudus", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1036", name: "Salami Al-Amin", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1047", name: "Doqh David", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1034", name: "Maikumo Mattavo", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1061", name: "Alimi Faruq", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1037", name: "Ademosu Hannah", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1004", name: "Abdul Umukatim", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1012", name: "Kotila Joseph", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1026", name: "Bwala Daniel", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1006", name: "Abdulazeez Abdulhannan", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1023", name: "Dikko Amina", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1002", name: "Adekilekun Fawaz", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1013", name: "Akanbi Dhul'Qarnain", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1050", name: "Ajaqbe Daniel", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1063", name: "Shuaibu Suleiman", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1020", name: "Bitrus Kazahyet", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1027", name: "Imo Daniel", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1016", name: "Ahmad Tijani", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1021", name: "Ibrahim Nurudeen", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1049", name: "Tanimowo Oluwafunmilade", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1029", name: "Nurudeen-Yusuf Mahmud", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1001", name: "Okono Etoroabasi", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1043", name: "Welson Justine", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1042", name: "Uduneje Chidiebube", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1008", name: "Garba Ndwaqhnom", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1045", name: "Adetola David", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1003", name: "Adams Ephraim", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1038", name: "Oscar Nekabari", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1025", name: "Abdulrahman Abdulmuhyi", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1033", name: "Gadi Stephanas", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1032", name: "Owoh Wisdom", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1009", name: "Adebiyi Folaromi", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1011", name: "Nasiru Usman", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1058", name: "Usman Gabriel", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1046", name: "Jisu Emmanuel", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1048", name: "Yusuf Aisha", department: "Mechatronics Engineering" },
    { matricNumber: "U24MTE1054", name: "Danladi Delight", department: "Mechatronics Engineering" },

    // Metallurgical & Materials Engineering (MME)
    { matricNumber: "U24MME1046", name: "Olaniyi Rokeeb", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1049", name: "Sunday Maksen", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1002", name: "Musa Ibrahim", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1042", name: "Sanusi Abdulaziz", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1039", name: "Shaqba Sydney", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1010", name: "EKUNDAYO ENIOLUWA", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1006", name: "Maiqida Kpeiknom", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1045", name: "Ahmed Abiodun", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1014", name: "Avantunji Georqina", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1055", name: "Eriki Andrew", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1023", name: "Dawam Gabriella", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1033", name: "Oladunjoye Precious", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1057", name: "Salaudeen Sofiat", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1022", name: "Aina Victor", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1026", name: "YIZOMA EMMANUEL", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1003", name: "Oladapo Benjamin", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1005", name: "Frank Prosper", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1038", name: "Sanni Rahmah", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1024", name: "Godwin Onyejefu", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1054", name: "Abdulrahman Habeeb", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1047", name: "Oqboqu Chukuemeka", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1050", name: "Onehi Aqaba", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1017", name: "Haruna Daniel", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1053", name: "Onwuzor Chibueze", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1018", name: "Amo Kerter", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1007", name: "Ebojei Divine", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1025", name: "Hwande Sesuqhter", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1004", name: "Peters Oluwaseyi", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1020", name: "Oluwole-Adeosun Daniel", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1041", name: "Adedayo Oluwakayode", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1028", name: "ESAN DAVID", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1059", name: "ANYANWO LOUIS", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1036", name: "KAMIR JUSTINE", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1048", name: "Abdulkadir Yusuf", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1021", name: "Neekpoa Victor", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1064", name: "Otuturu Solomon", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1008", name: "Kolawole Oluwakorede", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1031", name: "Audu David", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1011", name: "Sawyerr Timilehin", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1048", name: "Olajide Iseoluwa", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1015", name: "Olusegun Hephzibah", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1013", name: "Adeniyi Teninlanimi", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1039", name: "Musa Amir", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1009", name: "Omojola Oluwadamilola", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1019", name: "Yamoah Davidson", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1035", name: "Samuel Chideraa", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1036", name: "Chukwudindu Dominion", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1044", name: "Ibrahim Kelvin", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1034", name: "Gberindyer Kenneth", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1052", name: "Oloketuvi David", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1006", name: "Hunde Elijah", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1058", name: "AWAK ALEXANDER", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1043", name: "Samaila Esther", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1056", name: "Animashaun Emmanuel", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1001", name: "Bulus Stephen", department: "Metallurgical & Materials Engineering" },
    { matricNumber: "U24MME1037", name: "Ademosu Hannah", department: "Metallurgical & Materials Engineering" },


    // Telecommunications Engineering (TE)
    { matricNumber: "U24TE1034", name: "Obadele Ovie", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1050", name: "David Favour", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1014", name: "Adeyanju Abdulhamid", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1046", name: "Eqbe Tonna", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1006", name: "John Donald", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1020", name: "Philip Pedro", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1031", name: "Badrudeen Abdulsabur", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1016", name: "Amadi Godstar", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1045", name: "Shawon Beeve", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1013", name: "Abot Isaac", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1040", name: "Akande Winnifred", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1025", name: "Musa Jil", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1026", name: "Kafidipe Hassan", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1043", name: "Adewale Khalid", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1038", name: "Chukwuani Cephas", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1010", name: "Achilike Samuel-Mary", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1011", name: "Ndukwe Daniel", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1019", name: "Stephen Godsent", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1012", name: "Michael Divine", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1014_2", name: "Galadima Ritek", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1004", name: "EKONG CALEB", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1052", name: "Georqe Samprosper", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1022", name: "Nwankwo Goodness", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1015", name: "Omole Emmanuel", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1047", name: "Bako Alfred", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1027", name: "Hezekiah Royal", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1049", name: "Awanq Peter", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1003", name: "Fakolade David", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1039", name: "Peter Kelvin", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1051", name: "Job Gideon", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1024", name: "Adebayo Elizabeth", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1007", name: "Alabebe Kamolideen", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1044", name: "Edoho Churchill", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1035", name: "Obatave Prevail", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1008", name: "Ukazu Obed", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1021", name: "Gabriel Bright", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1028", name: "Salihu Abdulhaqq", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1036", name: "Sunday Mfonobong", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1029", name: "Ojochoqu Joshua", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1017", name: "Bastoni Xavier", department: "Telecommunications Engineering" },
    { matricNumber: "U24TE1001", name: "Marvis Favour", department: "Telecommunications Engineering" }
];

module.exports = students;
